#cloud-config
ssh_authorized_keys:
  - ${ssh_pub_key}

write_files:
  - path: /etc/vault.d/vault.hcl
    permissions: 0644
    owner: root
    content: |
      storage "s3" {
        region     = "eu-central-1"
        access_key = "${access_key}"
        secret_key = "${secret_key}"
        bucket     = "${s3_bucket}"
      }

      listener "tcp" {
        address     = "0.0.0.0:8200" # ONLY LOCAL HOST
        tls_disable = "true"
      }

      api_addr = "http://${private_ip_addr}:8200"
      cluster_addr = "https://${private_ip_addr}:8201"
      ui = true
      disable_mlock = true
  - path: /etc/systemd/system/vault.service
    permissions: 0644
    owner: root
    content: |
      [Unit]
      Description="HashiCorp Vault - A tool for managing secrets" Documentation=https://www.vaultproject.io/docs/
      Requires=network-online.target
      After=network-online.target ConditionFileNotEmpty=/etc/vault.d/vault.hcl
      StartLimitBurst=3

      [Service]
      Restart=on-failure
      RestartSec=10
      ExecStart=/usr/local/bin/vault server -config=/etc/vault.d/vault.hcl ExecReload=/bin/kill --signal HUP $MAINPID
      KillMode=process
      KillSignal=SIGINT
      Restart=on-failure
      RestartSec=5
      TimeoutStopSec=30
      StartLimitInterval=60
      StartLimitIntervalSec=60
      StartLimitBurst=3
      LimitNOFILE=65536
      LimitMEMLOCK=infinity

      [Install]
      WantedBy=multi-user.target