on: push
name: CI
jobs:

  build-and-push:
    name: build docker image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: build docker image
      uses: docker/build-push-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ github.repository }}
        tag_with_ref: true
        tag_with_sha: true
        tags: ${{ github.sha }}
        push: false
